- name: Deploy Windows Instances on ec2
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - win-nodes-ec2.yml
  vars:
    ansible_port: 5986
    windows: yes
  roles:
    - ec2-find-amis
    - ansible-role-ec2